export const VERSION_MVE = 'MVE';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const SEARCH_PRODUCTS_REQUEST = 'SERACH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SERACH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SERACH_PRODUCTS_FAIL';

export const FETCH_ONE_PRODUCT_REQUEST = 'FETCH_ONE_PRODUCT_REQUEST';
export const FETCH_ONE_PRODUCT_FAIL = 'FETCH_ONE_PRODUCT_FAIL';
export const FETCH_ONE_PRODUCT_SUCCESS = 'FETCH_ONE_PRODUCT_SUCCESS';

export const FETCH_COMMON_PRODUCTS_REQUEST = 'FETCH_COMMON_PRODUCTS_REQUEST';
export const FETCH_COMMON_PRODUCTS_FAIL = 'FETCH_COMMON_PRODUCTS_FAIL';
export const FETCH_COMMON_PRODUCTS_SUCCESS = 'FETCH_COMMON_PRODUCTS_SUCCESS';

export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_RESET_STATE = 'AUTH_RESET_STATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REGESTRATION_REQUEST = 'AUTH_REGESTRATION_REQUEST';
export const AUTH_REGESTRATION_SUCCESS = 'AUTH_REGESTRATION_SUCCESS';
export const AUTH_REGESTRATION_FAIL = 'AUTH_REGESTRATION_FAIL';

export const FETCH_PROFILE_FIELDS_REQUEST = 'FETCH_PROFILE_FIELDS_REQUEST';
export const FETCH_PROFILE_FIELDS_SUCCESS = 'FETCH_PROFILE_FIELDS_SUCCESS';
export const FETCH_PROFILE_FIELDS_FAIL = 'FETCH_PROFILE_FIELDS_FAIL';

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const REGISTER_DEVICE_REQUEST = 'REGISTER_DEVICE_REQUEST';
export const REGISTER_DEVICE_SUCCESS = 'REGISTER_DEVICE_SUCCESS';
export const REGISTER_DEVICE_FAIL = 'REGISTER_DEVICE_FAIL';

export const CART_LOADING = 'CART_LOADING';
export const CART_LOADED = 'CART_LOADED';

export const CART_SUCCESS = 'CART_SUCCESS';
export const CART_FAIL = 'CART_FAIL';

export const CART_CHANGE_REQUEST = 'CART_CHANGE_REQUEST';
export const CART_CHANGE_SUCCESS = 'CART_CHANGE_SUCCESS';
export const CART_CHANGE_FAIL = 'CART_CHANGE_FAIL';

export const CART_CLEAR_REQUEST = 'CART_CLEAR_REQUEST';
export const CART_CLEAR_SUCCESS = 'CART_CLEAR_SUCCESS';
export const CART_CLEAR_FAIL = 'CART_CLEAR_FAIL';

export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST';
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS';
export const CART_REMOVE_FAIL = 'CART_REMOVE_FAIL';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const CART_CONTENT_SAVE_REQUEST = 'CART_CONTENT_SAVE_REQUEST';
export const CART_CONTENT_SAVE_SUCCESS = 'CART_CONTENT_SAVE_SUCCESS';
export const CART_CONTENT_SAVE_FAIL = 'CART_CONTENT_SAVE_FAIL';

export const CART_RECALCULATE_REQUEST = 'CART_RECALCULATE_REQUEST';
export const CART_RECALCULATE_SUCCESS = 'CART_RECALCULATE_SUCCESS';
export const CART_RECALCULATE_FAIL = 'CART_RECALCULATE_FAIL';

export const CART_ADD_COUPON_CODE = 'CART_ADD_COUPON_CODE';
export const CART_ADD_COUPON_CODE_FAILED = 'CART_ADD_COUPON_CODE_FAILED';
export const CART_REMOVE_COUPON_CODE = 'CART_REMOVE_COUPON_CODE';

export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';

export const FETCH_PAGES_REQUEST = 'FETCH_PAGES_REQUEST';
export const FETCH_PAGES_SUCCESS = 'FETCH_PAGES_SUCCESS';
export const FETCH_PAGES_FAIL = 'FETCH_PAGES_FAIL';

export const SETTLEMENTS_REQUEST = 'SETTLEMENTS_REQUEST';
export const SETTLEMENTS_SUCCESS = 'SETTLEMENTS_SUCCESS';
export const SETTLEMENTS_FAIL = 'SETTLEMENTS_FAIL';

export const FETCH_LAYOUTS_BLOCKS_REQUEST = 'FETCH_LAYOUTS_BLOCKS_REQUEST';
export const FETCH_LAYOUTS_BLOCKS_SUCCESS = 'FETCH_LAYOUTS_BLOCKS_SUCCESS';
export const FETCH_LAYOUTS_BLOCKS_FAIL = 'FETCH_LAYOUTS_BLOCKS_FAIL';

export const BLOCK_CATEGORIES = 'categories';
export const BLOCK_BANNERS = 'banners';
export const BLOCK_PRODUCTS = 'products';
export const BLOCK_PAGES = 'pages';
export const BLOCK_VENDORS = 'vendors';

export const WISH_LIST_FETCH_REQUEST = 'WISH_LIST_FETCH_REQUEST';
export const WISH_LIST_FETCH_SUCCESS = 'WISH_LIST_FETCH_SUCCESS';
export const WISH_LIST_FETCH_FAIL = 'WISH_LIST_FETCH_FAIL';

export const WISH_LIST_ADD_REQUEST = 'WISH_LIST_ADD_REQUEST';
export const WISH_LIST_ADD_SUCCESS = 'WISH_LIST_ADD_SUCCESS';
export const WISH_LIST_ADD_FAIL = 'WISH_LIST_ADD_FAIL';

export const WISH_LIST_REMOVE_REQUEST = 'WISH_LIST_REMOVE_REQUEST';
export const WISH_LIST_REMOVE_SUCCESS = 'WISH_LIST_REMOVE_SUCCESS';
export const WISH_LIST_REMOVE_FAIL = 'WISH_LIST_REMOVE_FAIL';

export const WISH_LIST_CLEAR = 'WISH_LIST_CLEAR';

export const FETCH_DISCUSSION_REQUEST = 'FETCH_DISCUSSION_REQUEST';
export const FETCH_DISCUSSION_SUCCESS = 'FETCH_DISCUSSION_SUCCESS';
export const FETCH_DISCUSSION_FAIL = 'FETCH_DISCUSSION_FAIL';

export const POST_DISCUSSION_REQUEST = 'POST_DISCUSSION_REQUEST';
export const POST_DISCUSSION_SUCCESS = 'POST_DISCUSSION_SUCCESS';
export const POST_DISCUSSION_FAIL = 'POST_DISCUSSION_FAIL';

export const POST_SEND_REVIEW_REQUEST = 'POST_SEND_REVIEW_REQUEST';
export const POST_SEND_REVIEW_SUCCESS = 'POST_SEND_REVIEW_SUCCESS';
export const POST_SEND_REVIEW_FAIL = 'POST_SEND_REVIEW_FAIL';

export const DISCUSSION_DISABLED = 'D';
export const DISCUSSION_COMMUNICATION = 'C';
export const DISCUSSION_RATING = 'R';
export const DISCUSSION_COMMUNICATION_AND_RATING = 'B';

export const FETCH_VENDOR_REQUEST = 'FETCH_VENDOR_REQUEST';
export const FETCH_VENDOR_SUCCESS = 'FETCH_VENDOR_SUCCESS';
export const FETCH_VENDOR_FAIL = 'FETCH_VENDOR_FAIL';

export const FETCH_VENDOR_CATEGORIES_REQUEST =
  'FETCH_VENDOR_CATEGORIES_REQUEST';
export const FETCH_VENDOR_CATEGORIES_SUCCESS =
  'FETCH_VENDOR_CATEGORIES_SUCCESS';
export const FETCH_VENDOR_CATEGORIES_FAIL = 'FETCH_VENDOR_CATEGORIES_FAIL';

export const CHANGE_PRODUCTS_SORT = 'CHANGE_PRODUCTS_SORT';

export const FEATURE_TYPE_DATE = 'D';
export const FEATURE_TYPE_CHECKBOX = 'C';
export const FEATURE_TYPE_CHECKBOX_MULTIPLE = 'M';
export const FEATURE_TYPE_SELECT = 'S';

export const VENDOR_FETCH_PRODUCTS_REQUEST = 'VENDOR_FETCH_PRODUCTS_REQUEST';
export const VENDOR_FETCH_PRODUCTS_FAIL = 'VENDOR_FETCH_PRODUCTS_FAIL';
export const VENDOR_FETCH_PRODUCTS_SUCCESS = 'VENDOR_FETCH_PRODUCTS_SUCCESS';

export const VENDOR_FETCH_PRODUCT_REQUEST = 'VENDOR_FETCH_PRODUCT_REQUEST';
export const VENDOR_FETCH_PRODUCT_FAIL = 'VENDOR_FETCH_PRODUCT_FAIL';
export const VENDOR_FETCH_PRODUCT_SUCCESS = 'VENDOR_FETCH_PRODUCT_SUCCESS';

export const VENDOR_UPDATE_PRODUCT_REQUEST = 'VENDOR_UPDATE_PRODUCT_REQUEST';
export const VENDOR_UPDATE_PRODUCT_FAIL = 'VENDOR_UPDATE_PRODUCT_FAIL';
export const VENDOR_UPDATE_PRODUCT_SUCCESS = 'VENDOR_UPDATE_PRODUCT_SUCCESS';

export const VENDOR_DELETE_PRODUCT_REQUEST = 'VENDOR_DELETE_PRODUCT_REQUEST';
export const VENDOR_DELETE_PRODUCT_FAIL = 'VENDOR_DELETE_PRODUCT_FAIL';
export const VENDOR_DELETE_PRODUCT_SUCCESS = 'VENDOR_DELETE_PRODUCT_SUCCESS';

export const VENDOR_CREATE_PRODUCT_REQUEST = 'VENDOR_CREATE_PRODUCT_REQUEST';
export const VENDOR_CREATE_PRODUCT_FAIL = 'VENDOR_CREATE_PRODUCT_FAIL';
export const VENDOR_CREATE_PRODUCT_SUCCESS = 'VENDOR_CREATE_PRODUCT_SUCCESS';

export const RECALCULATE_PRODUCT_PRICE_REQUEST =
  'RECALCULATE_PRODUCT_PRICE_REQUEST';
export const RECALCULATE_PRODUCT_PRICE_FAIL = 'RECALCULATE_PRODUCT_PRICE_FAIL';
export const RECALCULATE_PRODUCT_PRICE_SUCCESS =
  'RECALCULATE_PRODUCT_PRICE_SUCCESS';

export const VENDOR_ORDERS_REQUEST = 'VENDOR_ORDERS_REQUEST';
export const VENDOR_ORDERS_FAIL = 'VENDOR_ORDERS_FAIL';
export const VENDOR_ORDERS_SUCCESS = 'VENDOR_ORDERS_SUCCESS';

export const VENDOR_ORDER_REQUEST = 'VENDOR_ORDER_REQUEST';
export const VENDOR_ORDER_FAIL = 'VENDOR_ORDER_FAIL';
export const VENDOR_ORDER_SUCCESS = 'VENDOR_ORDER_SUCCESS';

export const VENDOR_ORDER_UPDATE_STATUS_REQUEST =
  'VENDOR_ORDER_UPDATE_STATUS_REQUEST';
export const VENDOR_ORDER_UPDATE_STATUS_FAIL =
  'VENDOR_ORDER_UPDATE_STATUS_FAIL';
export const VENDOR_ORDER_UPDATE_STATUS_SUCCESS =
  'VENDOR_ORDER_UPDATE_STATUS_SUCCESS';

export const VENDOR_PRODUCT_CHANGE_CATEGORY = 'VENDOR_PRODUCT_CHANGE_CATEGORY';

export const VENDOR_CATEGORIES_TOGGLE = 'VENDOR_CATEGORIES_TOGGLE';
export const VENDOR_CATEGORIES_CLEAR = 'VENDOR_CATEGORIES_CLEAR';

export const IMAGE_PICKER_TOGGLE = 'IMAGE_PICKER_TOGGLE';
export const IMAGE_PICKER_CLEAR = 'IMAGE_PICKER_CLEAR';

export const STORE_KEY = '@REDUX_STORE_AUTH_KEY';
export const RESTORE_STATE = 'RESTORE_STATE';

export const USER_TYPE_VENDOR = 'V';

export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_CURRENCIES = 'GET_CURRENCIES';

export const LANGUAGE_CURRENCY_FEATURE_FLAG_OFF =
  'LANGUAGE_CURRENCY_FEATURE_FLAG_OFF';

export const FETCH_ORDER_STATUSES_REQUEST = 'FETCH_ORDER_STATUSES_REQUEST';
export const FETCH_ORDER_STATUSES_FAIL = 'FETCH_ORDER_STATUSES_FAIL';
export const FETCH_ORDER_STATUSES_SUCCESS = 'FETCH_ORDER_STATUSES_SUCCESS';

export const VENDOR_ORDERS_LOADED = 'VENDOR_ORDERS_LOADED';
export const VENDOR_ORDERS_LOADING = 'VENDOR_ORDERS_LOADING';

export const SET_FLOW = 'SET_FLOW';
export const SET_NEXT_STEP = 'SET_NEXT_STEP';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const SET_ADDONS_SETTINGS = 'SET_ADDONS_SETTINGS';

export const LIKE_DISLIKE_REVIEW_REQUEST = 'LIKE_DISLIKE_REVIEW_REQUEST';
export const LIKE_DISLIKE_REVIEW_SUCCESS = 'LIKE_DISLIKE_REVIEW_SUCCESS';
export const LIKE_DISLIKE_REVIEW_FAIL = 'LIKE_DISLIKE_REVIEW_FAIL';

export const SET_PRODUCT_REVIEWS = 'SET_PRODUCT_REVIEWS';
